<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JumpzysVortex.Network\JumpzysVortex.Network.csproj"/>
    <ProjectReference Include="..\JumpzysVortex.Services\JumpzysVortex.Services.csproj"/>
  </ItemGroup>
</Project>
