<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>vortex.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="vortex.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <ProjectReference Include="..\JumpzysVortex.App\JumpzysVortex.App.csproj"/>
    <ProjectReference Include="..\JumpzysVortex.Config\JumpzysVortex.Config.csproj"/>
  </ItemGroup>
</Project>
